In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',1000)

In [3]:
from utils.mesh import Ellipsoid
import torch
import torch.nn as nn
import torch.nn.functional as F

from models.layers.chamfer_wrapper import ChamferDist

In [4]:
import os
import pickle

import numpy as np
import torch
import trimesh
from scipy.sparse import coo_matrix

import config

In [5]:
a =  torch.Tensor([[2,14,11,4,-1,-1,-1,-1,1,4],[5,6,7,13,8,-1,-1,-1,2,5]])
print(a.size(-1))

10


In [ ]:
只是单纯实验

In [ ]:
a =  torch.Tensor([[2,14,11,4,-1,-1,-1,-1,1,4],[5,6,7,13,8,-1,-1,-1,2,5]])
b = a[:, :-2]
invalid_mask = b < 0
all_valid_indices = b
all_valid_indices[invalid_mask] = 0 
print(all_valid_indices)
inputs = np.array([[[2,3,4],[3,6,8],[-3,56,68],[23,-6,-8],[13,26,38],[43,-6,-8],[-3,-6,8],[3,-6,8],[-3,6,8],[-39,6,8],[53,6,8],[53,6,8],[63,6,28],[43,56,8],[43,56,28]]])

vertices = inputs[:, all_valid_indices]
print(vertices)

vertices[:, invalid_mask] = 0
neighbor_sum = torch.sum(vertices, 2)
neighbor_count = lap_idx[:, -1].float()
laplace = inputs - neighbor_sum / neighbor_count[None, :, None]

In [24]:
#example to test!
b =  np.array([[2,14,11,4,-1,-1,-1,-1,1,4],[5,6,7,13,8,-1,-1,-1,2,5]])
invalid_mask = b < 0
all_valid_indices = b
all_valid_indices[invalid_mask] = 0 
# print(all_valid_indices)
inputs = np.array([[[2,3,4],[3,6,8],[-3,56,68],[23,-6,-8],[13,26,38],[43,-6,-8],[-3,-6,8],[3,-6,8],[-3,6,8],[-39,6,8],[53,6,8],[53,6,8],[63,6,28],[43,56,8],[43,56,28]]])

vertices = inputs[:, all_valid_indices]
# print(vertices)

vertices[:, invalid_mask] = 0
neighbor_sum = np.sum(vertices, 2)
neighbor_count = b[:, -1]
print(neighbor_sum)
laplace = neighbor_sum / neighbor_count[None, :, None]
print(laplace)

[[[122 176 188]
  [123  94  84]]]
[[[30.5 44.  47. ]
  [24.6 18.8 16.8]]]


In [26]:
x1 = torch.Tensor([[[3,53,6],[2,82,36]]])
x2 = torch.Tensor([[[1,3,46],[2,832,336]]])
x3 = torch.Tensor([[[3,553,65],[52,852,436]]])
x = [x1,x2,x3]
print(x[1])
print(x[1][:,1])

tensor([[[  1.,   3.,  46.],
         [  2., 832., 336.]]])
tensor([[  2., 832., 336.]])


In [21]:
with open('datasets/data/ellipsoid/pixel2mesh_aux_4stages.dat', "rb") as fp:
            fp_info = pickle.load(fp, encoding='latin1')
# print(fp_info[0])# shape: n_pts * 3
# print(fp_info[1][1][0])
# print(fp_info)
laplace_idx = []
laplace_idx.append(torch.tensor(fp_info[7][0], dtype=torch.long))
print(laplace_idx)#very important!! laplace_idx is in a [], if we want to get out the number, we need add [0] first
neighbor_count = laplace_idx[0][:, -1].float()#-1 to represent None
print(neighbor_count[None, :, None])

[tensor([[  1,   2,   7,  ...,  -1,   0,   7],
        [  0,   2,   3,  ...,  -1,   1,   7],
        [  0,   1,   4,  ...,  -1,   2,   5],
        ...,
        [129, 132, 133,  ...,  -1, 153,   7],
        [135, 140, 142,  ...,  -1, 154,   5],
        [136, 137, 142,  ...,  -1, 155,   7]])]
tensor([[[7.],
         [7.],
         [5.],
         [6.],
         [8.],
         [4.],
         [7.],
         [7.],
         [5.],
         [5.],
         [6.],
         [5.],
         [6.],
         [7.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [5.],
         [6.],
         [7.],
         [5.],
         [7.],
         [6.],
         [4.],
         [5.],
         [7.],
         [6.],
         [5.],
         [7.],
         [4.],
         [6.],
         [6.],
         [5.],
         [5.],
         [7.],
         [5.],
         [7.],
         [4.],
         [7.],
         [6.],
         [6.],
         [7.],
         [5.],
         [6.],
   

In [32]:
edges = []
edges.append(torch.tensor(fp_info[1][1][0], dtype=torch.long))
print(edges[0])
print(edges[0][:,1])

tensor([[  0,   0],
        [  0,   1],
        [  0,   2],
        ...,
        [155, 153],
        [155, 154],
        [155, 155]])
tensor([  0,   1,   2,  ..., 153, 154, 155])


In [15]:
indices = laplace_idx[0]
invalid_mask = indices < 0
all_valid_indices = indices.clone()
all_valid_indices[invalid_mask] = 0  # do this to avoid negative indices
print(invalid_mask)
print(all_valid_indices)

tensor([[0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 1, 0, 0],
        ...,
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 1, 0, 0]], dtype=torch.uint8)
tensor([[  1,   2,   7,  ...,   0,   0,   7],
        [  0,   2,   3,  ...,   0,   1,   7],
        [  0,   1,   4,  ...,   0,   2,   5],
        ...,
        [129, 132, 133,  ...,   0, 153,   7],
        [135, 140, 142,  ...,   0, 154,   5],
        [136, 137, 142,  ...,   0, 155,   7]])


In [8]:
print(*fp_info[1][1])

[[  0   0]
 [  0   1]
 [  0   2]
 ...
 [155 153]
 [155 154]
 [155 155]] [ 0.35482302 -0.19354615 -0.22900689 ... -0.19354615 -0.22900689
  0.35482302] (156, 156)


In [9]:
# indices, value, size = *fp_info[1][1]

SyntaxError: can't use starred expression here (2067671154.py, line 4)

In [6]:

mesh_pos = [0., 0., -0.8]
ellipsoid = Ellipsoid(mesh_pos)

pd.set_option('display.max_columns',1000)
pd.set_option('max_row',300)
pd.set_option('display.float_format',lambda x:'%.5f' % x)

print(ellipsoid.edges)
print('################')
print(ellipsoid.laplace_idx[1])


[tensor([[  0,   0],
        [  0,   1],
        [  0,   2],
        ...,
        [155, 153],
        [155, 154],
        [155, 155]]), tensor([[  0,   0],
        [  0, 156],
        [  0, 157],
        ...,
        [617, 612],
        [617, 616],
        [617, 617]]), tensor([[   0,    0],
        [   0,  618],
        [   0,  619],
        ...,
        [2465, 2463],
        [2465, 2464],
        [2465, 2465]])]
################
tensor([[156, 157, 168,  ...,  -1,   0,   7],
        [156, 158, 159,  ...,  -1,   1,   7],
        [157, 158, 162,  ...,  -1,   2,   5],
        ...,
        [140, 154, 550,  ...,  -1, 615,   6],
        [142, 154, 557,  ...,  -1, 616,   6],
        [142, 155, 559,  ...,  -1, 617,   6]])


In [31]:
faces = []
obj_fmt_faces = []#usage??
        # faces: f * 3, original ellipsoid, and two after deformations
for i in range(1, 4):
    face_file = os.path.join('datasets/data/ellipsoid/', "face%d.obj" % i)
    faces = np.loadtxt(face_file, dtype='|S32')
    obj_fmt_faces.append(faces)
    print(obj_fmt_faces[0])
#     faces.append(torch.tensor(faces[:, 1:].astype(np.int) - 1))

[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]
[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]
[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]


In [48]:
gt_normal = torch.Tensor([[3,53,6],[2,82,36]])
print(gt_normal.shape)
indices = torch.Tensor([[1,0],[2,0]])
for t, i in zip(gt_normal, indices.long()):
    print(t)
    print('##############')
    print(i)
    print(t[i])
nearest_normals = torch.stack([t[i] for t, i in zip(gt_normal, indices.long())])#add one more []
print(nearest_normals)

torch.Size([2, 3])
tensor([ 3., 53.,  6.])
##############
tensor([1, 0])
tensor([53.,  3.])
tensor([ 2., 82., 36.])
##############
tensor([2, 0])
tensor([36.,  2.])
tensor([[53.,  3.],
        [36.,  2.]])
