In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',1000)

In [3]:
from utils.mesh import Ellipsoid
import torch
import torch.nn as nn
import torch.nn.functional as F

from models.layers.chamfer_wrapper import ChamferDist

In [4]:
import os
import pickle

import numpy as np
import torch
import trimesh
from scipy.sparse import coo_matrix

import config

In [5]:
a =  torch.Tensor([[2,14,11,4,-1,-1,-1,-1,1,4],[5,6,7,13,8,-1,-1,-1,2,5]])
print(a.size(-1))

10


In [ ]:
只是单纯实验

In [ ]:
a =  torch.Tensor([[2,14,11,4,-1,-1,-1,-1,1,4],[5,6,7,13,8,-1,-1,-1,2,5]])
b = a[:, :-2]
invalid_mask = b < 0
all_valid_indices = b
all_valid_indices[invalid_mask] = 0 
print(all_valid_indices)
inputs = np.array([[[2,3,4],[3,6,8],[-3,56,68],[23,-6,-8],[13,26,38],[43,-6,-8],[-3,-6,8],[3,-6,8],[-3,6,8],[-39,6,8],[53,6,8],[53,6,8],[63,6,28],[43,56,8],[43,56,28]]])

vertices = inputs[:, all_valid_indices]
print(vertices)

vertices[:, invalid_mask] = 0
neighbor_sum = torch.sum(vertices, 2)
neighbor_count = lap_idx[:, -1].float()
laplace = inputs - neighbor_sum / neighbor_count[None, :, None]

In [24]:
#example to test!
b =  np.array([[2,14,11,4,-1,-1,-1,-1,1,4],[5,6,7,13,8,-1,-1,-1,2,5]])
invalid_mask = b < 0
all_valid_indices = b
all_valid_indices[invalid_mask] = 0 
# print(all_valid_indices)
inputs = np.array([[[2,3,4],[3,6,8],[-3,56,68],[23,-6,-8],[13,26,38],[43,-6,-8],[-3,-6,8],[3,-6,8],[-3,6,8],[-39,6,8],[53,6,8],[53,6,8],[63,6,28],[43,56,8],[43,56,28]]])

vertices = inputs[:, all_valid_indices]
# print(vertices)

vertices[:, invalid_mask] = 0
neighbor_sum = np.sum(vertices, 2)
neighbor_count = b[:, -1]
print(neighbor_sum)
laplace = neighbor_sum / neighbor_count[None, :, None]
print(laplace)

[[[122 176 188]
  [123  94  84]]]
[[[30.5 44.  47. ]
  [24.6 18.8 16.8]]]


In [26]:
x1 = torch.Tensor([[[3,53,6],[2,82,36]]])
x2 = torch.Tensor([[[1,3,46],[2,832,336]]])
x3 = torch.Tensor([[[3,553,65],[52,852,436]]])
x = [x1,x2,x3]
print(x[1])
print(x[1][:,1])

tensor([[[  1.,   3.,  46.],
         [  2., 832., 336.]]])
tensor([[  2., 832., 336.]])


In [5]:
with open('datasets/data/semi-sphere/semi-sphere.dat', "rb") as fp:
            fp_info = pickle.load(fp, encoding='latin1')
# print(fp_info[0])# shape: n_pts * 3
# print(fp_info[1][1][0])
# print(fp_info)
laplace_idx = []
laplace_idx.append(torch.tensor(fp_info[7][0], dtype=torch.long))
print(laplace_idx)#very important!! laplace_idx is in a [], if we want to get out the number, we need add [0] first
neighbor_count = laplace_idx[0][:, -1].float()#-1 to represent None
print(neighbor_count[None, :, None])

[tensor([[0, 0, 0, 0]])]
tensor([[[0.]]])


In [6]:
edges = []
edges.append(torch.tensor(fp_info[1][1][0], dtype=torch.long))
print(edges[0])
print(edges[0][:,1])

tensor([[  0,   0],
        [  0,   1],
        [  0,   3],
        ...,
        [140,  77],
        [140, 138],
        [140, 140]])
tensor([  0,   1,   3,  69,  72,  73,   0,   1,   2,   3,   4,  70,  72,   1,
          2,   4,   5,  70,  71,   0,   1,   3,   4,   6,   8,   9,  10,  73,
          1,   2,   3,   4,   5,   7,   8,   2,   4,   5,   7,  11,  71, 124,
          3,   6,   9,  13,  73,  74, 104, 106,   4,   5,   7,   8,  11,  14,
         15,  16,   3,   4,   7,   8,  10,  12,  15,   3,   6,   9,  10,  13,
          3,   8,   9,  10,  12,  13,  20,   5,   7,  11,  14,  17, 124,   8,
         10,  12,  15,  20,  21,  29,   6,   9,  10,  13,  20, 106, 107,   7,
         11,  14,  16,  17,  18,  19,  24,   7,   8,  12,  15,  16,  29,   7,
         14,  15,  16,  18,  22,  26,  29,  32,  11,  14,  17,  24,  27, 124,
        127,  14,  16,  18,  22,  14,  19,  24,  28,  10,  12,  13,  20,  21,
         23,  25, 107,  12,  20,  21,  23,  29,  30,  31,  16,  18,  22,  26,
        

In [7]:
indices = laplace_idx[0]
invalid_mask = indices < 0
all_valid_indices = indices.clone()
all_valid_indices[invalid_mask] = 0  # do this to avoid negative indices
print(invalid_mask)
print(all_valid_indices)

tensor([[0, 0, 0, 0]], dtype=torch.uint8)
tensor([[0, 0, 0, 0]])


In [8]:
print(*fp_info[1][1])

[[  0   0]
 [  0   1]
 [  0   3]
 ...
 [140  77]
 [140 138]
 [140 140]] [ 0.22327143 -0.22333778 -0.1934162  -0.1729967  -0.20677061 -0.24465429
 -0.22333778  0.22327143 -0.22333778 -0.17656402 -0.20387857 -0.20387857
 -0.18875488 -0.22333778  0.22327143 -0.22333778 -0.22333778 -0.22333778
 -0.22333778 -0.1934162  -0.17656402  0.22327143 -0.17656402 -0.16346652
 -0.17656402 -0.21624588 -0.17656402 -0.1934162  -0.20387857 -0.22333778
 -0.17656402  0.22327143 -0.20387857 -0.18875488 -0.20387857 -0.22333778
 -0.20387857  0.22327143 -0.18875488 -0.22333778 -0.20387857 -0.17656402
 -0.16346652  0.22327143 -0.23117657 -0.18875488 -0.20677061 -0.15411771
 -0.23117657 -0.20677061 -0.18875488 -0.18875488  0.22327143 -0.18875488
 -0.20677061 -0.17475306 -0.20677061 -0.16346652 -0.17656402 -0.20387857
 -0.18875488  0.22327143 -0.20387857 -0.20387857 -0.22333778 -0.21624588
 -0.23117657  0.22327143 -0.24969923 -0.24969923 -0.17656402 -0.20387857
 -0.24969923  0.22327143 -0.20387857 -0.20387857 -0.

In [9]:
# indices, value, size = *fp_info[1][1]

SyntaxError: can't use starred expression here (2067671154.py, line 4)

In [6]:

mesh_pos = [0., 0., -0.8]
ellipsoid = Ellipsoid(mesh_pos)

pd.set_option('display.max_columns',1000)
pd.set_option('max_row',300)
pd.set_option('display.float_format',lambda x:'%.5f' % x)

print(ellipsoid.edges)
print('################')
print(ellipsoid.laplace_idx[1])


[tensor([[  0,   0],
        [  0,   1],
        [  0,   2],
        ...,
        [155, 153],
        [155, 154],
        [155, 155]]), tensor([[  0,   0],
        [  0, 156],
        [  0, 157],
        ...,
        [617, 612],
        [617, 616],
        [617, 617]]), tensor([[   0,    0],
        [   0,  618],
        [   0,  619],
        ...,
        [2465, 2463],
        [2465, 2464],
        [2465, 2465]])]
################
tensor([[156, 157, 168,  ...,  -1,   0,   7],
        [156, 158, 159,  ...,  -1,   1,   7],
        [157, 158, 162,  ...,  -1,   2,   5],
        ...,
        [140, 154, 550,  ...,  -1, 615,   6],
        [142, 154, 557,  ...,  -1, 616,   6],
        [142, 155, 559,  ...,  -1, 617,   6]])


In [20]:
faces = []
obj_fmt_faces = []#usage??
        # faces: f * 3, original ellipsoid, and two after deformations
for i in range(1, 5):
    # face_file = os.path.join('datasets/data/ellipsoid/', "face%d.obj" % i)
    face_file = os.path.join('datasets/data/semi-sphere/', "semi%d.obj" % i)
    faces = np.genfromtxt(face_file, dtype='|S32')
    obj_fmt_faces.append(faces)
    print(obj_fmt_faces[0])
#     faces.append(torch.tensor(faces[:, 1:].astype(np.int) - 1))

[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]
[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]
[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]
[[b'f' b'1' b'2' b'3']
 [b'f' b'2' b'4' b'5']
 [b'f' b'3' b'2' b'5']
 ...
 [b'f' b'143' b'141' b'155']
 [b'f' b'156' b'143' b'155']
 [b'f' b'143' b'156' b'137']]


In [48]:
gt_normal = torch.Tensor([[3,53,6],[2,82,36]])
print(gt_normal.shape)
indices = torch.Tensor([[1,0],[2,0]])
for t, i in zip(gt_normal, indices.long()):
    print(t)
    print('##############')
    print(i)
    print(t[i])
nearest_normals = torch.stack([t[i] for t, i in zip(gt_normal, indices.long())])#add one more []
print(nearest_normals)

torch.Size([2, 3])
tensor([ 3., 53.,  6.])
##############
tensor([1, 0])
tensor([53.,  3.])
tensor([ 2., 82., 36.])
##############
tensor([2, 0])
tensor([36.,  2.])
tensor([[53.,  3.],
        [36.,  2.]])
